alias aliases='nvim ~/.bash_aliases'
alias vimrc='nvim ~/.config/nvim/init.vim'
alias bashrc='nvim ~/.bashrc'
alias global_vars='sudo nvim /etc/environment'
alias profile='nvim ~/.profile'
alias g++safe='g++ -Wall -Wextra -Wshadow -ansi -Wconversion -Wsign-conversion -pedantic-errors -Werror'
